services:
  recruit-bot:
    container_name: recruit-bot
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile

    volumes:
      - ../..:/workspaces:cached
    working_dir: /workspace
    environment:
        POSTGRES_PASSWORD: postgres
        POSTGRES_USER: postgres
        POSTGRES_DB: postgres
        POSTGRES_HOSTNAME: db
    command: sleep infinity
    ports:
      - 4983:4983

  db:
    container_name: recruit-bot-pg
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    expose:
        - "5432"
    

volumes:
    postgres-data: